[env:nodemcuv2]
platform  = espressif8266
board     = nodemcuv2
framework = arduino

board_build.filesystem = littlefs

monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    tzapu/WiFiManager @ ^2.0.17
    knolleary/PubSubClient @ ^2.8
    https://github.com/adafruit/ENS160_driver.git
    adafruit/Adafruit AHTX0 @ ^2.0.5
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    bblanchon/ArduinoJson @ ^7.0.4
    jandrassy/TelnetStream @ ^1.3.0

[env:nodemcuv2_ota]
extends         = env:nodemcuv2
upload_protocol = espota
upload_port     = extractor-esp.local
monitor_port    = socket://extractor-esp.local:23

[env:nodemcuv2_ota_ip]
extends         = env:nodemcuv2
upload_protocol = espota
upload_port     = 192.168.4.1
monitor_port    = socket://192.168.4.1:23